import * as fs from 'fs';
import * as path from 'path';

interface TestCase {
  id: string;
  title: string;
  priority: string;
  type: string;
  steps: string[];
  expectedResult: string;
}

function toTestName(tc: TestCase): string {
  return `${tc.id} [${tc.priority}/${tc.type}] ${tc.title}`;
}

function generateSpecFile(testCases: TestCase[], sourceName: string): string {
  const header = `/**
 * AUTO-GENERATED TEST STUBS
 * Source requirement: ${sourceName}
 * Generated by AI (Gemini) from requirement text — steps below are AI-suggested.
 * Each test is marked fixme() until a human implements and verifies it.
 */
import { test, expect } from '@playwright/test';

test.describe('${sourceName.replace(/\.md$/, '')}', () => {
`;

  const body = testCases
    .map((tc) => {
      const stepsComment = tc.steps.map((s) => `    // - ${s}`).join('\n');
      return `  test.fixme('${toTestName(tc).replace(/'/g, "\\'")}', async ({ page }) => {
    // Steps (AI-suggested, implement below):
${stepsComment}
    // Expected result:
    //   ${tc.expectedResult}

    // TODO: implement using LoginPage / InventoryPage or raw locators
  });`;
    })
    .join('\n\n');

  return header + body + '\n});\n';
}

async function main() {
  const jsonFile = process.argv[2];
  if (!jsonFile) {
    console.error('Usage: npx tsx src/ai/generateTestFile.ts <json-file-name>');
    console.error('Example: npx tsx src/ai/generateTestFile.ts add-to-cart.json');
    process.exit(1);
  }

  const jsonPath = path.join('generated', jsonFile);
  if (!fs.existsSync(jsonPath)) {
    console.error(`File not found: ${jsonPath}`);
    process.exit(1);
  }

  const testCases: TestCase[] = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
  const specContent = generateSpecFile(testCases, jsonFile);

  const outputName = jsonFile.replace(/\.json$/, '.generated.spec.ts');
  const outputDir = path.join('tests', 'generated');
  fs.mkdirSync(outputDir, { recursive: true });
  const outputPath = path.join(outputDir, outputName);

  fs.writeFileSync(outputPath, specContent);
  console.log(`Wrote ${testCases.length} test stubs to ${outputPath}`);
}

main();